const Color = [
    "AliceBlue ", 
    "AntiqueWhite" ,
    "Aqua" ,
    "Aquamarine" ,
    "Azure ", 
    "Beige ", 
    "Bisque ", 
    "Black ", 
    "BlanchedAlmond ", 
    "Blue" ,
    "BlueViolet" ,
    "Brown" ,
    "BurlyWood" ,
    "CadetBlue" ,
    "Chartreuse" ,
    "Chocolate" ,
    "Coral" ,
    "CornflowerBlue" ,
    "Cornsilk" ,
    "Crimson" ,
    "Cyan" ,
    "DarkBlue" ,
    "DarkCyan" ,
    "DarkGoldenRod" ,
    "DarkGray" ,
    "DarkGrey" ,
    "DarkGreen" ,
    "DarkKhaki" ,
    "DarkMagenta" ,
    "DarkOliveGreen" ,
    "DarkOrange" ,
    "DarkOrchid" ,
    "DarkRed" ,
    "DarkSalmon" ,
    "DarkSeaGreen" ,
    "DarkSlateBlue" ,
    "DarkSlateGray" ,
    "DarkSlateGrey" ,
    "DarkTurquoise" ,
    "DarkViolet" ,
    "DeepPink" ,
    "DeepSkyBlue" ,
    "DimGray" ,
    "DimGrey" ,
    "DodgerBlue" ,
    "FireBrick" ,
    "FloralWhite" ,
    "ForestGreen" ,
    "Fuchsia" ,
    "Gainsboro" ,
    "GhostWhite" ,
    "Gold" ,
    "GoldenRod" ,
    "Gray" ,
    "Grey" ,
    "Green" ,
    "GreenYellow" ,
    "HoneyDew" ,
    "HotPink" ,
    "IndianRed" ,
    "Indigo" ,
    "Ivory" ,
    "Khaki" ,
    "Lavender" ,
    "LavenderBlush" ,
    "LawnGreen" ,
    "LemonChiffon" ,
    "LightBlue" ,
    "LightCoral" ,
    "LightCyan" ,
    "LightGoldenRodYellow" ,
    "LightGray" ,
    "LightGrey" ,
    "LightGreen" ,
    "LightPink" ,
    "LightSalmon" ,
    "LightSeaGreen" ,
    "LightSkyBlue" ,
    "LightSlateGray" ,
    "LightSlateGrey" ,
    "LightSteelBlue" ,
    "LightYellow" ,
    "Lime" ,
    "LimeGreen" ,
    "Linen" ,
    "Magenta" ,
    "Maroon" ,
    "MediumAquaMarine" ,
    "MediumBlue" ,
    "MediumOrchid" ,
    "MediumPurple" ,
    "MediumSeaGreen" ,
    "MediumSlateBlue" ,
    "MediumSpringGreen" ,
    "MediumTurquoise" ,
    "MediumVioletRed" ,
    "MidnightBlue" ,
    "MintCream" ,
    "MistyRose" ,
    "Moccasin" ,
    "NavajoWhite" ,
    "Navy" ,
    "OldLace" ,
    "Olive" ,
    "OliveDrab" ,
    "Orange" ,
    "OrangeRed" ,
    "Orchid" ,
    "PaleGoldenRod" ,
    "PaleGreen" ,
    "PaleTurquoise" ,
    "PaleVioletRed" ,
    "PapayaWhip" ,
    "PeachPuff" ,
    "Peru" ,
    "Pink" ,
    "Plum" ,
    "PowderBlue" ,
    "Purple" ,
    "RebeccaPurple" ,
    "Red" ,
    "RosyBrown" ,
    "RoyalBlue" ,
    "SaddleBrown" ,
    "Salmon" ,
    "SandyBrown" ,
    "SeaGreen" ,
    "SeaShell" ,
    "Sienna" ,
    "Silver" ,
    "SkyBlue" ,
    "SlateBlue" ,
    "SlateGray" ,
    "SlateGrey" ,
    "Snow" ,
    "SpringGreen" ,
    "SteelBlue" ,
    "Tan" ,
    "Teal" ,
    "Thistle" ,
    "Tomato" ,
    "Turquoise" ,
    "Violet" ,
    "Wheat" ,
    "White" ,
    "WhiteSmoke" ,
    "Yellow" ,
    "YellowGreen" ,
    ];

  const btn1=document.getElementById("btn1");
  const btn2=document.getElementById("btn2");
  const color = document.getElementById("input-box");
  const change = document.getElementById("change");

  btn1.addEventListener("click" , function(){
      let random=randomColor();
      document.body.style.backgroundColor = Color[random];
      color.value = Color[random];
  });

  btn2.addEventListener("click" , function(){
    document.body.style.backgroundColor = "Gray";
  });
  
  change.addEventListener("click",function(){
    let value=color.value;
    for(let i=0;i<Color.length;i++){
      if(Color[i].toUpperCase==value.toUpperCase){
        document.body.style.backgroundColor = value;
        return;
      }
    }
  });

  function randomColor(){
      return Math.floor(Math.random()*Color.length);
  }